name: SSH to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Connect to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connected successfully"
     
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # - name: Terraform Init (S3 Backend)
      #   run: |
      #     terraform init -reconfigure \
      #       -backend-config="bucket=conditional_approval" \
      #       -backend-config="key=terraform/state.tfstate" \
      #       -backend-config="region=ca-central-1"

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
         
      - name: Terraform Apply
        run: terraform apply -auto -approve

    # # This enforces manual approval in GitHub "Environments"
    # environment: production

    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.KEY_ID }}
    #   AWS_DEFAULT_REGION: ca-central-1

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Setup Terraform
    #     uses: hashicorp/setup-terraform@v3

    #     # - name: Terraform Init (S3 Backend)
    #   #   run: |
    #   #     terraform init -reconfigure \
    #   #       -backend-config="bucket=conditional_approval" \
    #   #       -backend-config="key=terraform/state.tfstate" \
    #   #       -backend-config="region=ca-central-1"

    #   - name: Terraform Init
    #     run: terraform init -reconfigure

    #   - name: Download Plan Artifact
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: tfplan

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve tfplan
